#!/bin/bash -l
#PBS -q workq
#PBS -A qris-uq
#PBS -N slim_supp_112
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=24:mem=120G

cd $TMPDIR


module load R/3.5.0

R --file=/home/$USER/SLiM/Scripts/Nimrod/Final/AIM3/R/AIM3_supp_unix.R


cat /${TMPDIR}/out_8T_stabsel_means.csv >> /30days/${USER}/out_8T_stabsel_means_112.csv

cat /${TMPDIR}/out_8T_stabsel_muts.csv >> /30days/${USER}/out_8T_stabsel_muts_112.csv

cat /${TMPDIR}/out_8T_stabsel_chr.csv >> /30days/${USER}/out_8T_stabsel_chr_112.csv

cat /${TMPDIR}/out_8T_stabsel_burnin.csv >> /30days/${USER}/out_8T_stabsel_burnin_112.csv

cat /${TMPDIR}/out_8T_stabsel_opt.csv >> /30days/${USER}/out_8T_stabsel_opt_112.csv
