#!/bin/bash -l
#PBS -q workq
#PBS -A qris-uq
#PBS -N slim_matrix_example
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:mem=24G

cd $TMPDIR


mkdir -p ./matrices/model1

module load R/3.5.0

R --file=/home/$USER/SLiM/Scripts/8T100L_stabsel_fxtest.R

zip -r /30days/$USER/matrix_example/matrices.zip /$TMPDIR/matrices

cat /$TMPDIR/out_8T_stabsel_means.csv >> /30days/$USER/out_8T_stabsel_means.csv

cat /$TMPDIR/out_8T_stabsel_muts.csv >> /30days/$USER/out_8T_stabsel_muts.csv

cat /$TMPDIR/out_8T_stabsel_chr.csv >> /30days/$USER/out_8T_stabsel_chr.csv

cat /$TMPDIR/out_8T_recom_burnin.csv >> /30days/$USER/out_8T_recom_burnin.csv