#!/bin/bash -l
#PBS -q workq
#PBS -A qris-uq
#PBS -N slim_matrix_example
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=20:mem=120G

cd $TMPDIR

MAX=0
MIN=1

mkdir -p ./matrices/model{0..1}

module load R/3.5.0

R --file=/home/$USER/SLiM/Scripts/matrix_example_unix.R

zip -r /30days/$USER/matrix_example/matrices.zip /$TMPDIR/matrices

cat /$TMPDIR/out_8T100L_null_means.csv >> /30days/$USER/out_8T100L_null_means.csv

cat /$TMPDIR/out_8T100L_null_means.csv >> /30days/$USER/out_8T100L_null_muts.csv

cat /$TMPDIR/out_8T100L_null_chr.csv >> /30days/$USER/out_8T100L_null_chr.csv