#!/bin/bash -l
#PBS -q workq
#PBS -A qris-uq
#PBS -N slim_null2T_array
#PBS -J 1-30
#PBS -l walltime=160:00:00
#PBS -l select=1:ncpus=24:mem=120G

cd $TMPDIR

MAX=$((PBS_ARRAY_INDEX*5))

MIN=$((PBS_ARRAY_INDEX*5-4))

mkdir -p $(seq --format './matrices/model%.0f' $MIN $MAX)

module load R/3.5.0

echo "Array index = $PBS_ARRAY_INDEX"

R --file=/home/$USER/SLiM/Scripts/2traits_jobarray_unix.R

zip -r /30days/$USER/matrices_${PBS_ARRAY_INDEX}.zip /$TMPDIR/matrices

cat /$TMPDIR/out_2T100L_means.csv >> /30days/$USER/out_8T100L_null_means.csv

cat /$TMPDIR/out_2T100L_muts.csv >> /30days/$USER/out_8T100L_null_muts.csv
