#!/bin/bash -l
#PBS -q workq
#PBS -A qris-uq
#PBS -N slim_sel8T_array
#PBS -J 1-100
#PBS -l walltime=368:00:00 # Will need ~1735 hours for final run if we have all 10,000 runs
#PBS -l select=1:ncpus=24:mem=120G

cd $TMPDIR

mkdir -p ./matrices/model${PBS_ARRAY_INDEX}

module load R/3.5.0

echo "Array index = $PBS_ARRAY_INDEX"

R --file=/home/$USER/SLiM/Scripts/AIM3_jobarray_unix.R

zip -r /30days/$USER/matrices_${PBS_ARRAY_INDEX}.zip /$TMPDIR/matrices

cat /$TMPDIR/out_8T_stabsel_means.csv >> /30days/$USER/out_8T_stabsel_means.csv

cat /$TMPDIR/out_8T_stabsel_muts.csv >> /30days/$USER/out_8T_stabsel_muts.csv

cat /$TMPDIR/out_8T_stabsel_chr.csv >> /30days/$USER/out_8T_stabsel_chr.csv

cat /$TMPDIR/out_8T_stabsel_burnin.csv >> /30days/$USER/out_8T_stabsel_burnin.csv
