#!/bin/bash -l
#PBS -q workq
#PBS -A qris-uq
#PBS -N slim_sel8T_pilot
#PBS -l walltime=336:00:00
#PBS -l select=1:ncpus=24:mem=120G

cd $TMPDIR

mkdir -p ./matrices/model{1..9}

module load R/3.5.0

R --file=/home/$USER/SLiM/Scripts/Pilot/AIM3_pilot_unix.R

zip -r /30days/$USER/matrices_sel_pilot.zip /$TMPDIR/matrices

cat /$TMPDIR/out_8T_stabsel_means.csv >> /30days/$USER/out_8T_stabsel_means.csv

cat /$TMPDIR/out_8T_stabsel_muts.csv >> /30days/$USER/out_8T_stabsel_muts.csv

cat /$TMPDIR/out_8T_stabsel_chr.csv >> /30days/$USER/out_8T_stabsel_chr.csv

cat /$TMPDIR/out_8T_stabsel_burnin.csv >> /30days/$USER/out_8T_stabsel_burnin.csv
